 Viết gọn trong 1 câu truy vấn các yêu cầu sau, sử dụng bảng DIM_CUSTOMER_PROFILE:
   1. Lấy tổng số giải ngân 6 tháng gần nhất.

SELECT CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) AS [PERIOD] 
	  ,EOMONTH(DISBURSEMENT_DATE)                AS [EOMONTH] 
	  ,SUM(LOAN_AMOUNT)							 AS [DISB_MAT]
FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) > CONVERT(NVARCHAR(7),(SELECT EOMONTH(CAST(MAX(DISBURSEMENT_DATE) AS DATE),-6) FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]),23)
GROUP BY CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23),EOMONTH(DISBURSEMENT_DATE) 

   2. Lấy tồng số khoản vay 6 tháng gần nhất.

SELECT CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) AS 'PERIOD'
,COUNT(LOAN_ACCOUNT_NUMBER) AS "COUNT_LOAN"
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)> CONVERT(NVARCHAR(7),(SELECT EOMONTH(CAST(MAX(DISBURSEMENT_DATE) AS DATE),-6) FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE),23)
GROUP BY CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)
ORDER BY CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) DESC

   3. Lấy tổng số giải ngân tháng gần nhất.

SELECT CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) AS 'PERIOD'
		,FORMAT(SUM(LOAN_AMOUNT),'#,##0;(#,##0)') AS 'SUM'
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) > CONVERT(NVARCHAR(7),(SELECT EOMONTH(CAST(MAX(DISBURSEMENT_DATE) AS DATE),-1) FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE),23)
GROUP BY CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)

   4. Lấy tồng số khoản vay tháng gần nhất.
   
SELECT CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) AS [PERIOD]
,COUNT(LOAN_ACCOUNT_NUMBER) AS 'SUM'
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) > CONVERT(NVARCHAR(7),(SELECT EOMONTH(CAST(MAX(DISBURSEMENT_DATE) AS DATE),-1) FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE),23)
GROUP BY CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)



--TẤT CẢ CÁC BÀI BÊN DƯỚI ĐỚI VỚI BẢNG FACT_LOAN_MANAGEMENT VÀ FACT_LOAN_COLLECTION CHỐT VỀ THÁNG BÁO CÁO LÀ 2023-12-31

-- Bài 1: Phân tích chất lượng giải ngân theo vùng từ bảng DIM_CUSTOMER_PROFILE
-- Yêu cầu: Thống kê số lượng khoản vay, tổng giải ngân, lãi suất trung bình, và số lượng khoản vay có bảng lương ngân hàng theo từng vùng
--AGGREGATE FUNCTION









-- Bài 2: Phân tích khoản vay theo độ tuổi từ bảng DIM_CUSTOMER_PROFILE 
-- Yêu cầu: Phân nhóm khách hàng theo độ tuổi và thống kê phân nhóm thu nhập, tổng số tiền vay, lãi suất trung bình





SELECT * FROM RISK_PORTFOLIO..FACT_LOAN_MANAGEMENT
--Sử dụng bảng RISK_PORTFOLIO..FACT_LOAN_MANAGEMENT --> CHỐT VỀ "WHERE REPORT_DATE = '2023-12-31'"
--Bài 3: Tổng dư nợ (OUTSTANDING ~ PRINCIPAL AMOUNT ~ ENR (ENDING NET RECEIVABLE)) 
--Tổng nợ xấu (OUTSTANDING với DPD > 90)--NPL: NON-PERFORMING LOAN LÀ TỶ LỆ NỢ XẤU
-- Ticket Size (SUM(LOAN_AMOUNT) / COUNT(LOAN_ACCOUNT_NO)) 
--Tổng số tiền WO (OUTSTANDING với DPD > 180), Tổng khoản vay (LOAN_ACCOUNT_NO) 
--Tổng khoản vay bị nợ xấu (Những LOAN_ACCOUNT_NO có DPD > 90) 
-- Tổng khoản vay bị WO (DPD > 180) 

SELECT POS = SUM(OUTSTANDING_AMOUNT)
	, ENR=SUM(CASE WHEN DPD<180 THEN OUTSTANDING_AMOUNT ELSE 0 END)
	, OD3PLUS = SUM(CASE WHEN DPD>90 AND DPD<180  THEN OUTSTANDING_AMOUNT ELSE 0 END)
	, [DPD90+] = SUM(CASE WHEN DPD>90 THEN OUTSTANDING_AMOUNT ELSE 0 END)
	, [OD3PLUS+]=COUNT(CASE WHEN DPD>90 AND DPD<180 THEN LOAN_ACCOUNT_NUMBER END)
	, WO_AMOUNT=SUM(CASE WHEN DPD>=180 THEN OUTSTANDING_AMOUNT ELSE 0 END)
	,WO_COUNT=COUNT(CASE WHEN DPD>=180 THEN LOAN_ACCOUNT_NUMBER END)
FROM RISK_PORTFOLIO..FACT_LOAN_MANAGEMENT
WHERE REPORT_DATE='2023-12-31'



SELECT REPORT_DATE
,FORMAT(SUM(CASE WHEN(DPD<180) THEN (OUTSTANDING_AMOUNT) ELSE 0 END),'#,##0;(#,##0)') AS [TONG DU NO] 
,FORMAT(SUM(CASE WHEN(DPD>90 AND DPD<180) THEN OUTSTANDING_AMOUNT ELSE 0 END),'#,##0;(#,##0)') AS [TONG NO XAU-NPL-NON PERFORMING LOAN]
,SUM(LOAN_AMOUNT)/COUNT(LOAN_ACCOUNT_NUMBER) AS [TICKET SIZE]
,SUM(CASE WHEN(DPD>=180) THEN [OUTSTANDING_AMOUNT] ELSE 0 END) AS [TONG WO]
,COUNT(LOAN_ACCOUNT_NUMBER) AS [TONG KHOAN VAY]
,SUM(CASE WHEN (DPD>=180) THEN OUTSTANDING_AMOUNT ELSE 0 END) AS [TONG KHOAN VAY NO XAU]
,COUNT(CASE WHEN (DPD>=180) THEN LOAN_ACCOUNT_NUMBER END) AS [TONG KHOAN VAY BI WO]
FROM RISK_PORTFOLIO..FACT_LOAN_MANAGEMENT
WHERE REPORT_DATE = '2023-12-31'
GROUP BY REPORT_DATE



USE RISK_PORTFOLIO 

SELECT * FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE

/*Không sử dụng set điều kiện bằng tay, thiết kế câu Query sao cho tự động theo thời gian mà không phải chỉnh tay*/

--1. Lấy TOP 10 khoản vay có số tiền giải ngân lớn nhất của 2 tháng trước kể từ tháng gần nhất - Sử dụng bảng: [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE].
SELECT EOMONTH(MAX(DISBURSEMENT_DATE)) FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE
SELECT DATEADD(MONTH,-2,SELECT EOMONTH(MAX(DISBURSEMENT_DATE)) FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE)

SELECT TOP 10 LOAN_AMOUNT,LOAN_ACCOUNT_NUMBER,DISB_MONTH=CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)=CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,-2,(SELECT EOMONTH(MAX(DISBURSEMENT_DATE)) FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE))),23)
ORDER BY LOAN_AMOUNT DESC

SELECT TOP 10 LOAN_AMOUNT,CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) AS DISB_MONTH,LOAN_ACCOUNT_NUMBER
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)=CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,-1,(SELECT EOMONTH(MAX(DISBURSEMENT_DATE))FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE))),23)
ORDER BY LOAN_AMOUNT DESC

SELECT TOP 10 LOAN_AMOUNT,CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)AS DISB_PERIOD,LOAN_ACCOUNT_NUMBER
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)=CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,0,(SELECT(EOMONTH(MAX(DISBURSEMENT_DATE))) FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE))),23)
ORDER BY LOAN_AMOUNT DESC

SELECT TOP 10 LOAN_AMOUNT,CONVERT(NVARCHAR(10),DISBURSEMENT_DATE,23)AS DISB_PERIOD,LOAN_ACCOUNT_NUMBER
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)>CONVERT(NVARCHAR(7),(SELECT EOMONTH(CAST(MAX(DISBURSEMENT_DATE) AS DATE),-3) FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE),23)
ORDER BY LOAN_AMOUNT DESC


SELECT TOP 10 LOAN_AMOUNT,CONVERT(NVARCHAR(10),DISBURSEMENT_DATE,23) AS 'DISB_PERIOD'
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) > CONVERT(NVARCHAR(7),(SELECT EOMONTH(CAST(MAX(DISBURSEMENT_DATE) AS DATE),-3) FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE),23)
ORDER BY LOAN_AMOUNT DESC

--2. Sản phẩm nào có số tiền giải ngân lớn nhất của tháng gần nhất - Sử dụng bảng: [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE].

SELECT TOP 1 PRODUCT_NAME,SUM(LOAN_AMOUNT) AS [DISB_MAX]
	  ,CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) AS [PERIOD] 
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)= CONVERT(NVARCHAR(7),(SELECT EOMONTH(CAST(MAX(DISBURSEMENT_DATE) AS DATE),0) FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE),23)
GROUP BY PRODUCT_NAME,CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)
ORDER BY SUM(LOAN_AMOUNT) DESC 

SELECT PRODUCT_NAME,SUM(LOAN_AMOUNT) AS [DISB_MAX]
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)= CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,0,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE))FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE))),23)
GROUP BY PRODUCT_NAME,LOAN_ACCOUNT_NUMBER
ORDER BY SUM(LOAN_AMOUNT) DESC 

SELECT PRODUCT_NAME,SUM(LOAN_AMOUNT) AS [DISB_MAX]
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)= CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,0,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE))FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE))),23)
GROUP BY PRODUCT_NAME,CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)
ORDER BY SUM(LOAN_AMOUNT) DESC 

SELECT EOMONTH(CAST(MAX(DISBURSEMENT_DATE) AS DATE),0) FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE
SELECT DATEADD(MONTH,0,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE))FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE))

--3. Thống kê số tiền giải ngân của mỗi sáng phẩm trong 6 tháng gần nhất - Sử dụng bảng: [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE] (Gợi ý sử dụng SUM(CASE WHEN....) cho từng sản phẩm và GROUP BY theo tháng với FORMAT YYYY-MM của DISBURSEMENT_DATE)

--CÁCH GIANG BAI
DECLARE @DISB_0 NVARCHAR(7)=CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,0,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE))FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE))),23)
DECLARE @DISB_1 NVARCHAR(7)=CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,-1,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE))FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE))),23)
DECLARE @DISB_2 NVARCHAR(7)=CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,-2,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE))FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE))),23)
DECLARE @DISB_3 NVARCHAR(7)=CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,-3,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE))FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE))),23)
DECLARE @DISB_4 NVARCHAR(7)=CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,-4,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE))FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE))),23)
DECLARE @DISB_5 NVARCHAR(7)=CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,-5,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE))FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE))),23)
DECLARE @DISB_6 NVARCHAR(7)=CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,-6,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE))FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE))),23)

SELECT PRODUCT_NAME
		,[DISB_MONTH_0]=SUM(CASE WHEN CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)= @DISB_0 THEN LOAN_AMOUNT ELSE 0 END)
		,[DISB_MONTH_1]=SUM(CASE WHEN CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)= @DISB_1 THEN LOAN_AMOUNT ELSE 0 END)
		,[DISB_MONTH_2]=SUM(CASE WHEN CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)= @DISB_2 THEN LOAN_AMOUNT ELSE 0 END)
		,[DISB_MONTH_3]=SUM(CASE WHEN CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)= @DISB_3 THEN LOAN_AMOUNT ELSE 0 END)
		,[DISB_MONTH_4]=SUM(CASE WHEN CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)= @DISB_4 THEN LOAN_AMOUNT ELSE 0 END)
		,[DISB_MONTH_5]=SUM(CASE WHEN CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)= @DISB_5 THEN LOAN_AMOUNT ELSE 0 END)
		,[DISB_MONTH_6]=SUM(CASE WHEN CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)= @DISB_6 THEN LOAN_AMOUNT ELSE 0 END)
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE
GROUP BY PRODUCT_NAME



SELECT CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) AS [PERIOD]
,SUM(CASE WHEN PRODUCT_NAME = 'G-Gold' THEN LOAN_AMOUNT ELSE 0 END) AS 'G-Gold'
,SUM(CASE WHEN PRODUCT_NAME = 'T-Titanium' THEN LOAN_AMOUNT ELSE 0 END) AS 'T-Titanium'
,SUM(CASE WHEN PRODUCT_NAME = 'B-BROWN' THEN LOAN_AMOUNT ELSE 0 END) AS 'B-BROWN'
,SUM(CASE WHEN PRODUCT_NAME = 'INSURANCE' THEN LOAN_AMOUNT ELSE 0 END) AS 'INSURANCE'
,SUM(CASE WHEN PRODUCT_NAME = 'VAY_PLUS' THEN LOAN_AMOUNT ELSE 0 END) AS 'VAY_PLUS'
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)> CONVERT(NVARCHAR(7),(SELECT EOMONTH(CAST(MAX(DISBURSEMENT_DATE) AS DATE),-7) FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE),23)
GROUP BY CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)


--4. Tỉnh nào có nhiều khoản vay nhất vào năm ngoái - Sử dụng bảng: [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE].

SELECT TOP 1 COUNT(LOAN_ACCOUNT_NUMBER) AS [COUNT_LOAN_AMOUNT],PROVINCE
,CONVERT(NVARCHAR(4),DISBURSEMENT_DATE,23) AS [PERIOD]
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE CONVERT(NVARCHAR(4),DISBURSEMENT_DATE,23) < DATEADD(YEAR,-1,(SELECT MAX(DISBURSEMENT_DATE) FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE))
GROUP BY CONVERT(NVARCHAR(4),DISBURSEMENT_DATE,23),PROVINCE
ORDER BY COUNT(LOAN_ACCOUNT_NUMBER) DESC

SELECT TOP 1 PROVINCE
,ACCT_CNT = COUNT(LOAN_ACCOUNT_NUMBER)
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE YEAR(DISBURSEMENT_DATE)=(SELECT YEAR(DATEADD(YEAR,-1,(SELECT MAX(DISBURSEMENT_DATE)FROM [RISK_PORTFOLIO]..DIM_CUSTOMER_PROFILE))))
GROUP BY PROVINCE
ORDER BY COUNT(LOAN_ACCOUNT_NUMBER)DESC

SELECT DATEADD(YEAR,-1,(SELECT MAX(DISBURSEMENT_DATE)FROM [RISK_PORTFOLIO]..DIM_CUSTOMER_PROFILE))

SELECT * FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
--5. Lấy TOP 10 tỉnh có số tiền giải ngân vào Quý 1 và Quý 2 năm ngoái - Sử dụng bảng: [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE].


SELECT TOP 10 DISBURSEMENT_DATE,PROVINCE,SUM(LOAN_AMOUNT)
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE
WHERE DATEPART(QUARTER,DISBURSEMENT_DATE) IN ('01') AND YEAR(DISBURSEMENT_DATE) = '2022'
GROUP BY PROVINCE,DISBURSEMENT_DATE
ORDER BY DISBURSEMENT_DATE DESC


--6. Lấy ENR và WO amount theo tháng (chốt cuối tháng: REPORT_DATE = EOMONTH(REPORT_DATE)) - Sử dụng bảng: [RISK_PORTFOLIO]..[FACT_LOAN_MANAGEMENT] (Gợi ý sử dụng SUM(CASE WHEN....) cho từng điều kiện ENR và WO theo tháng với chốt cuối tháng của REPORT_DATE)
			/*
			   ENR: DPD <= 180 
			   WO: DPD < 180 
			*/
--7. Lập báo cáo giải ngân theo tuần - theo dõi SẢN PHẨM, GIỚI TÍNH, TỈNH THÀNH, KHU VỰC, LOẠI THU NHẬP - Sử dụng bảng: [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE].

DECLARE @REPORT_DATE DATE = (SELECT MAX(EOMONTH(DISBURSEMENT_DATE)) FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE)
DECLARE @WEEK_4 DATE = (SELECT DATEADD(DAY,-7,@REPORT_DATE))
DECLARE @WEEK_3 DATE = (SELECT DATEADD(DAY,-7,@WEEK_4))
DECLARE @WEEK_2 DATE = (SELECT DATEADD(DAY,-7,@WEEK_3))
DECLARE @WEEK_1 DATE = (SELECT DATEADD(DAY,-7,@WEEK_2))
DECLARE @WEEK_0 DATE = (SELECT DATEADD(DAY,-7,@WEEK_1))

SELECT PRODUCT_NAME
	,[WEEK4]=SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK_4 AND DISBURSEMENT_DATE >@WEEK_3 THEN LOAN_AMOUNT ELSE 0 END)
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE
GROUP BY PRODUCT_NAME






