SELECT * FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE

--1. Tìm khách hàng có khoản vay trên 200 triệu
SELECT LOAN_ACCOUNT_NUMBER, FORMAT (LOAN_AMOUNT,'#,##0;(#,##0)') AS LOAN_AMOUNT FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE LOAN_AMOUNT >= 200*POWER(10,6) ORDER BY LOAN_AMOUNT DESC
SELECT LOAN_ACCOUNT_NUMBER,LOAN_AMOUNT FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE LOAN_AMOUNT > 200*POWER(10,6) ORDER BY LOAN_AMOUNT DESC

--2. Tìm khách hàng có thu nhập trên 100 triệu và là nhân viên văn phòng (cột collar worker).
SELECT CUSTOMER_NAME,LOAN_ACCOUNT_NUMBER,FORMAT(INCOME,'#,##0;(#,##0)')AS INCOME FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE INCOME >= 100000000 AND OCCUPATION LIKE '%Collar Worker%'
SELECT CUSTOMER_NAME,LOAN_ACCOUNT_NUMBER,INCOME,OCCUPATION FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE INCOME > 100*POWER(10,6) AND OCCUPATION LIKE '%Collar Worker%'

DTI: DEBT TO INCOME --> TY LE NO TREN THU NHAP.
LTV: LOAN TO VALUE --.

--3. Tìm khách hàng có DTI dưới 30% và thu nhập trên 50 triệu (cột DTI được hiểu là DEBT AMOUNT ~ DTI = DEBT AMOUNT / INCOME)
SELECT CUSTOMER_NAME,LOAN_ACCOUNT_NUMBER FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE %(LOAN_AMOUNT/INCOME) <= 30% AND INCOME > 50000000
(CÂU NÀY LÀM CÁCH TRÊN THÌ LÀM SAO???)

SELECT LOAN_ACCOUNT_NUMBER,LOAN_AMOUNT,INCOME,LOAN_AMOUNT/INCOME*100 AS DTI FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE LOAN_AMOUNT/INCOME*100 < 30 AND INCOME >= 50000000 ORDER BY DTI DESC
SELECT LOAN_ACCOUNT_NUMBER,LOAN_AMOUNT,DTI AS DEBT_AMT,DTI/INCOME AS DTI FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE (DTI/INCOME) < 0.3 AND INCOME > 50*POWER(10,6) ORDER BY DTI DESC

--4. Tìm khách hàng có khoản vay từ 100-200 triệu ở miền Nam
SELECT LOAN_ACCOUNT_NUMBER,CUSTOMER_NAME,LOAN_AMOUNT,PROVINCE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE REGION = 'South' AND LOAN_AMOUNT BETWEEN (100*POWER(10,6)) AND (200*POWER(10,6))

--5. Tìm khách hàng có lãi suất trên 40% và thời hạn trên 24 tháng
SELECT LOAN_ACCOUNT_NUMBER,CUSTOMER_NAME,LOAN_AMOUNT, TENOR, INTEREST_RATE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE INTEREST_RATE >40 AND TENOR >24 ORDER BY INTEREST_RATE DESC

--6. Tìm khách hàng có thu nhập dưới 15 triệu và khoản vay dưới 100 triệu
SELECT LOAN_ACCOUNT_NUMBER,CUSTOMER_NAME,LOAN_AMOUNT,INCOME FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE INCOME <= 15*POWER(10,6) AND LOAN_AMOUNT <= 100*POWER(10,6) ORDER BY INCOME DESC

--7. Tìm khách hàng có trình độ đại học và thu nhập trên 30 triệu
SELECT LOAN_ACCOUNT_NUMBER,CUSTOMER_NAME,INCOME, EDUCATION FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE INCOME >= 30000000 AND EDUCATION = 'University' ORDER BY INCOME ASC
SELECT LOAN_ACCOUNT_NUMBER,CUSTOMER_NAME,INCOME, EDUCATION FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE INCOME >= 30*POWER(10,6) AND EDUCATION LIKE '%Univer%' ORDER BY INCOME ASC

--8. Tìm khách hàng nam ở Hồ Chí Minh có khoản vay trên 300 triệu
SELECT CUSTOMER_NAME, LOAN_AMOUNT,GENDER,PROVINCE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE GENDER = 'Nam' AND PROVINCE LIKE '%H_%Ch_%Minh%' AND LOAN_AMOUNT >100*POWER(10,6) ORDER BY LOAN_AMOUNT DESC
SELECT CUSTOMER_NAME, LOAN_AMOUNT,GENDER,PROVINCE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE GENDER = 'Nam' AND PROVINCE LIKE '%H%Ch%Minh%' AND LOAN_AMOUNT >100*POWER(10,6) ORDER BY LOAN_AMOUNT DESC
SELECT CUSTOMER_NAME, LOAN_AMOUNT,GENDER,PROVINCE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE GENDER = 'Nam' AND PROVINCE LIKE '%Minh%' AND LOAN_AMOUNT >100*POWER(10,6) ORDER BY LOAN_AMOUNT DESC
SELECT CUSTOMER_NAME, LOAN_AMOUNT,GENDER,PROVINCE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE GENDER = 'Nam' AND PROVINCE LIKE N'Hồ Chí Minh' AND LOAN_AMOUNT >100*POWER(10,6) ORDER BY LOAN_AMOUNT DESC

--9. Tìm khách hàng có sản phẩm VAY_PLUS và thời hạn 36 tháng
SELECT CUSTOMER_NAME,PRODUCT_NAME,LOAN_AMOUNT,TENOR FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE PRODUCT_NAME LIKE '%VAY%PLUS%' AND TENOR = 36 

--10. Tìm khách hàng có ngày giải ngân trong tháng 6/2023
SELECT CUSTOMER_NAME,LOAN_AMOUNT,DISBURSEMENT_DATE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE MONTH(DISBURSEMENT_DATE)=6 AND YEAR (DISBURSEMENT_DATE)=2023

SELECT CUSTOMER_NAME,LOAN_AMOUNT,CAST(DISBURSEMENT_DATE AS DATE) AS DISBURSEMENT_DATE --CHUYEN YYYY-MM-DD hh:mm:ss thanh YYYY-MM-DD 
,CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) AS DISB_PERIOD
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)= '2023-06'


--2023-06-30
--23: LAY DINH DANG YYYY-MM-DD
--NVARCHAR(7): LAY 7 KY TU TU TRAI QUA PHAI

--11. Tìm khách hàng có thu nhập từ kinh doanh và DTI trên 40%
SELECT CUSTOMER_NAME,LOAN_AMOUNT,INCOME_TYPE,LOAN_AMOUNT/INCOME*100 AS DTI FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE INCOME_TYPE LIKE '%Business owed%' AND LOAN_AMOUNT/INCOME*100 >= 40 ORDER BY DTI DESC
SELECT CUSTOMER_NAME,LOAN_AMOUNT,INCOME_TYPE,DTI AS DEBT_AMOUNT,DTI/INCOME AS DTI FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE INCOME_TYPE LIKE '%Business%' AND DTI/INCOME > 0.4 ORDER BY DTI DESC

--12. Tìm khách hàng có địa chỉ ở đường Nguyễn Huệ
SELECT CUSTOMER_NAME,LOAN_AMOUNT,ADDRESS  FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE ADDRESS LIKE N'%Nguyễn Huệ%'
SELECT CUSTOMER_NAME,LOAN_AMOUNT,ADDRESS  FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE ADDRESS LIKE N'%Nguy_n%Hu_%'

--13. Tìm khách hàng có lãi suất từ 25%-30% và là nữ
SELECT CUSTOMER_NAME,INTEREST_RATE,GENDER FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE INTEREST_RATE BETWEEN 25 AND 30 AND GENDER = N'Nữ' ORDER BY INTEREST_RATE DESC

--14. Tìm khách hàng có sản phẩm B-BROWN và thu nhập trên 40 triệu
SELECT CUSTOMER_NAME,FORMAT(INCOME,'#,##0;(#,##0)') AS INCOME,PRODUCT_NAME FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE PRODUCT_NAME LIKE '%B-BROWN%' AND INCOME >= 40*POWER(10,6) ORDER BY FORMAT(INCOME,'#,##0;(#,##0)') DESC
SELECT CUSTOMER_NAME,INCOME,PRODUCT_NAME FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE PRODUCT_NAME = 'B-BROWN' AND INCOME >= 40*POWER(10,6) 
SELECT CUSTOMER_NAME,INCOME,PRODUCT_NAME FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE PRODUCT_NAME LIKE '%B%BROWN%' AND INCOME >= 40*POWER(10,6)

--15. Tìm khách hàng có ngày thanh toán đầu tiên trong tháng 7/2023
SELECT CUSTOMER_NAME,FIRST_PAYMENT_DATE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE MONTH(FIRST_PAYMENT_DATE)=7 AND YEAR(FIRST_PAYMENT_DATE)=2023
SELECT TOP 1 CUSTOMER_NAME,FIRST_PAYMENT_DATE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE CONVERT(NVARCHAR(7),FIRST_PAYMENT_DATE,23)='2023-07' ORDER BY FIRST_PAYMENT_DATE ASC

--16. Tìm khách hàng có thu nhập từ lương và khoản vay trên 150 triệu
SELECT CUSTOMER_NAME,INCOME_TYPE,FORMAT(LOAN_AMOUNT,'#,##0;(#,##0)')AS LOAN_AMOUNT FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE LOAN_AMOUNT >= 150*POWER(10,6) AND INCOME_TYPE LIKE '%Payslip%'  ORDER BY LOAN_AMOUNT ASC
SELECT CUSTOMER_NAME,INCOME_TYPE,LOAN_AMOUNT FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE LOAN_AMOUNT >= 150*POWER(10,6) AND INCOME_TYPE IN ('Bank Statement','Payslip')  ORDER BY LOAN_AMOUNT ASC
SELECT DISTINCT INCOME_TYPE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE

--17. Tìm khách hàng có thời hạn vay 12 tháng và lãi suất dưới 30% 
SELECT CUSTOMER_NAME,TENOR,INTEREST_RATE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE TENOR = '12' AND INTEREST_RATE < 30

--18. Tìm khách hàng có thu nhập trên 70 triệu ở miền Trung
SELECT CUSTOMER_NAME,REGION,FORMAT(INCOME,'#,##0;(#,##0)')AS INCOME_FORMAT FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE REGION ='Central' AND INCOME>=70*POWER(10,6) ORDER BY INCOME DESC

--19. Tìm khách hàng có khoản vay dưới 50 triệu và DTI dưới 20%
SELECT CUSTOMER_NAME,LOAN_AMOUNT/INCOME*100 AS DTI,FORMAT(LOAN_AMOUNT,'#,##0;(#,##0') AS LOAN_AMOUNT FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE LOAN_AMOUNT/INCOME*100 <= 20 AND LOAN_AMOUNT <= 50*POWER (10,6)

--20. Tìm khách hàng có tên họ Nguyễn và thu nhập trên 60 triệu
SELECT CUSTOMER_NAME, FORMAT(INCOME,'#,##0;(#,##0)') AS INCOME FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE CUSTOMER_NAME LIKE N'Nguyễn%' AND INCOME >= 60*POWER(10,6) ORDER BY INCOME DESC
SELECT CUSTOMER_NAME, FORMAT(INCOME,'#,##0;(#,##0)') AS INCOME_FORMAT FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE CUSTOMER_NAME LIKE 'Nguy_n%' AND INCOME >= 60*POWER(10,6) ORDER BY INCOME DESC

--21. Tìm khách hàng có sản phẩm INSURANCE và thời hạn trên 24 tháng
SELECT CUSTOMER_NAME,PRODUCT_NAME,TENOR FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE TENOR >= 24 AND PRODUCT_NAME LIKE '%INSURANCE%'

--22. Tìm khách hàng giới tính Nam có thu nhập trên 80 triệu ở Hà Nội
SELECT CUSTOMER_NAME,PROVINCE,GENDER,FORMAT(INCOME,'#,##0;(#,##0)') AS INCOME FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE PROVINCE = N'Hà Nội' AND GENDER ='Nam' AND INCOME >= 80*POWER(10,6) ORDER BY INCOME DESC

--23. Tìm khách hàng có ngày giải ngân trong quý 1/2023
SELECT CUSTOMER_NAME,DISBURSEMENT_DATE,DATEPART(QUARTER,DISBURSEMENT_DATE)AS [QUÝ] FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE DATEPART(QUARTER,DISBURSEMENT_DATE) = 3 AND YEAR(DISBURSEMENT_DATE)=2023 ORDER BY DISBURSEMENT_DATE ASC

SELECT CUSTOMER_NAME,DISBURSEMENT_DATE,DATEPART(QUARTER,DISBURSEMENT_DATE)AS [QUÝ] FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE DISBURSEMENT_DATE BETWEEN '2023-07-01' AND '2023-09-30' ORDER BY DISBURSEMENT_DATE ASC 

SELECT CUSTOMER_NAME,DISBURSEMENT_DATE,CONCAT(N'QUY',' ',DATEPART(QUARTER,DISBURSEMENT_DATE),'/',YEAR(DISBURSEMENT_DATE)),CONCAT (N'dU LIEU THAY DI THEO THANG, CAN LUU Y',' - ',YEAR(DISBURSEMENT_DATE)) AS [NOTE] FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE DATEPART(QUARTER,DISBURSEMENT_DATE) = 3 AND YEAR(DISBURSEMENT_DATE)=2023 ORDER BY DISBURSEMENT_DATE ASC

--24. Tìm khách hàng có khoản vay từ 200-300 triệu và lãi suất dưới 35%
SELECT CUSTOMER_NAME,LOAN_AMOUNT,INTEREST_RATE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE LOAN_AMOUNT BETWEEN 50*POWER(10,6) AND 100*POWER(10,6) AND INTEREST_RATE < 35  ORDER BY LOAN_AMOUNT DESC

--25. Tìm khách hàng có địa chỉ ở đường Lê Lợi và khoản vay trên 100 triệu
SELECT CUSTOMER_NAME,ADDRESS,LOAN_AMOUNT FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE ADDRESS LIKE N'%Lê Lợi%' AND LOAN_AMOUNT >= 100*POWER(10,6) ORDER BY LOAN_AMOUNT DESC
SELECT CUSTOMER_NAME,ADDRESS,LOAN_AMOUNT FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE [ADDRESS] LIKE '%L_%L_i%' AND LOAN_AMOUNT >= 100*POWER(10,6) ORDER BY LOAN_AMOUNT DESC

--26. Tìm khách hàng có thu nhập từ kinh doanh và khoản vay dưới 80 triệu
SELECT CUSTOMER_NAME,INCOME_TYPE,LOAN_AMOUNT FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE INCOME_TYPE LIKE '%Business%' AND LOAN_AMOUNT <= 80*POWER(10,6) ORDER BY LOAN_AMOUNT DESC

--27. Tìm khách hàng có lãi suất trên 45% và thu nhập dưới 25 triệu
SELECT CUSTOMER_NAME,INTEREST_RATE,INCOME FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE INTEREST_RATE >= 45 AND INCOME <= 25*POWER(10,6) ORDER BY INCOME DESC

--28. Tìm khách hàng nữ có khoản vay từ 150-250 triệu ở miền Nam
SELECT CUSTOMER_NAME,GENDER,REGION,LOAN_AMOUNT FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE GENDER LIKE N'%Nữ%' AND REGION LIKE '%South%' AND LOAN_AMOUNT BETWEEN 150*POWER(10,6) AND 250*POWER(10,6) ORDER BY LOAN_AMOUNT DESC

SELECT CUSTOMER_NAME,GENDER,REGION,LOAN_AMOUNT FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE GENDER = N'Nữ' AND REGION = 'South' AND LOAN_AMOUNT BETWEEN 150*POWER(10,6) AND 250*POWER(10,6) ORDER BY LOAN_AMOUNT DESC

