
USE RISK_PORTFOLIO


---SELECT *  FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE

---SELECT *  FROM RISK_PORTFOLIO.dbo.DIM_CUSTOMER_PROFILE

---SELECT *  FROM RISK_PORTFOLIO..FACT_LOAN_MANAGEMENT 

---SELECT *  FROM RISK_PORTFOLIO..FACT_LOAN_COLLECTION

---------------------------LƯU Ý-----------------------
--Mô tả cấu trúc của 1 bảng dữ liệu hoàn chỉnh: RISK_PORTFOLIO.dbo.DIM_CUSTOMER_PROFILE
--"RISK_PORTFOLIO": DATABASE NAME
--"dbo": là SCHEMA mặc định trong SQL - còn gọi là default 
--"DIM_CUSTOMER_PROFILE": là TABLE NAME 

--Cách kiểm tra cấu trúc bảng trong Microsoft SQL Server 
--INFORMATION_SCHEMA.TABLES: Bảng truy vấn thông tin của 1 DATABASE, bảng này là bảng có sẵn trên MS SQL Server, do nhà sản xuất cung cấp sẵn trên sản phẩm.
--Câu lệnh: SELECT * FROM INFORMATION_SCHEMA.TABLES

--Câu lệnh đầy đủ: SELECT *  FROM RISK_PORTFOLIO.dbo.DIM_CUSTOMER_PROFILE 

--Câu lệnh đầy đủ: SELECT *  FROM RISK_PORTFOLIO.dbo.FACT_LOAN_MANAGEMENT 

--Câu lệnh đầy đủ: SELECT *  FROM RISK_PORTFOLIO.dbo.FACT_LOAN_COLLECTION 

---CÂU LỆNH KIỂM TRA BẢNG DỮ LIỆU, TRƯỜNG DỮ LIỆU CÓ TRONG DATABASE ĐƯỢC GRANT QUYỀN 

--CÂU LỆNH 1: 

--Định nghĩa: "Trường dữ liệu" hay "Cột dữ liệu" hoặc "Biến" là một ~ Attribute  
--Định nghĩa: "Bản ghi" hay "Dòng dữ liệu" là một ~ Record 

SELECT *  FROM RISK_PORTFOLIO.dbo.DIM_CUSTOMER_PROFILE 

SELECT * FROM INFORMATION_SCHEMA.TABLES ---Câu lệnh kiểm tra có bao nhiêu bảng dữ liệu trong DATABASE --Trước khi chạy câu này phải chọn DATABASE ở trên.

SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME LIKE '%INCOME%' --Câu lệnh tìm kiếm những trường dữ liệu mình cần ở một bảng dữ liệu nào đó mà mình chưa biết.

SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME LIKE '%INCOME%TYPE%'

SELECT DISTINCT TABLE_NAME,COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME LIKE '%DIM_CUSTOMER_PROFILE%'

--CÂU LỆNH 2: 

SELECT * FROM sys.tables 

---CÂU LỆNH CƠ BẢN TRÍCH XUẤT DỮ LIỆU TRÊN SQL VỚI DẤU "*"


---NẾU CHỈ KIỂM TRA TRONG 1 BẢNG DỮ LIỆU CÓ NHỮNG TRƯỜNG DỮ LIỆU GÌ THÌ MÌNH DÙNG CÂU LỆNH SELECT DISTINCT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME LIKE '%DIM_CUSTOMER_PROFILE%'

SELECT 
       *
FROM RISK_PORTFOLIO.dbo.DIM_CUSTOMER_PROFILE


SELECT 
       LOAN_ACCOUNT_NUMBER
	  ,CUSTOMER_NAME
	  ,LOAN_AMOUNT
FROM RISK_PORTFOLIO.dbo.DIM_CUSTOMER_PROFILE

/*
		STEP 1: SELECT 
		STEP 2: Sử dụng dấu "*" để chọn toàn bộ trường dữ liệu trong bảng dữ liệu HOẶC gõ ra những trường dữ liệu mình cần và cách nhau bởi dấu phẩy 
		STEP 3: FROM [DATABASE].[SCHEMA].[TABLE_NAME]
*/


---CÂU LỆNH CƠ BẢN TRÍCH XUẤT DỮ LIỆU TRÊN SQL VỚI VIỆC CHỌN TỪNG CỘT 

SELECT 
       TOP 2 * --LẤY TOP TRONG TRƯỜNG HỢP KHÔNG CÓ ĐIỀU KIỆN GIỐNG VẦY THÌ CHỈ LẤY "RANDOM" -- LẤY TOP BAO NHIÊU CŨNG ĐƯỢC 
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE


SELECT 
           TOP 5 
           LOAN_ACCOUNT_NUMBER
		  ,INCOME
		  ,GENDER
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE --GÕ CỤ THỂ TÊN CỘT CẦN DÙNG ĐỂ TỐI ƯU HÓA HIỆU SUẤT CỦA CÂU TRUY VẤN 

SELECT     TOP 5 *
          ,LOAN_ACCOUNT_NUMBER
		  ,INCOME
		  ,GENDER
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE --GÕ CỤ THỂ TÊN CỘT CẦN DÙNG ĐỂ TỐI ƯU HÓA HIỆU SUẤT CỦA CÂU TRUY VẤN 


--CÁC CÁCH ĐẶT TÊN CỘT: "BETTER SAFE THAN SORRY" 

--CÁCH DÙNG NGOẶC VUÔNG 
SELECT 
		  LOAN_ACCOUNT_NUMBER AS [KHẾ ƯỚC NHẬN NỢ]
		 ,DISBURSEMENT_DATE   AS [THỜI ĐIỂM GIẢI NGÂN]
		 ,LOAN_AMOUNT         AS [SỐ TIỀN GIẢI NGÂN]
		 ,[ADDRESS]
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE  

SELECT 
		  LOAN_ACCOUNT_NUMBER KHE_UOC_NHAN_NO
		 ,DISBURSEMENT_DATE   THOI_DIEM_GIAI_NGAN
		 ,LOAN_AMOUNT         SO_TIEN_GIAI_NGAN
		 ,[ADDRESS]
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE  


--CÁCH DÙNG DẤU NHÁY ĐÔI 

SELECT 
		  LOAN_ACCOUNT_NUMBER AS "KHẾ ƯỚC NHẬN NỢ"
		 ,DISBURSEMENT_DATE   AS "THỜI ĐIỂM GIẢI NGÂN"
		 ,LOAN_AMOUNT         AS "SỐ TIỀN GIẢI NGÂN"
		 ,"ADDRESS"
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE  


--CÁCH DÙNG DẤU NHÁY ĐƠN
SELECT 
		  LOAN_ACCOUNT_NUMBER AS 'KHẾ ƯỚC NHẬN NỢ'
		 ,DISBURSEMENT_DATE   AS 'THỜI ĐIỂM GIẢI NGÂN'
		 ,LOAN_AMOUNT         AS 'SỐ TIỀN GIẢI NGÂN'
		 ,[ADDRESS]
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE  

--CÁCH DÙNG DẤU = ĐỂ ĐẶT TÊN CỘT 

SELECT 
		  [KHẾ ƯỚC NHẬN NỢ]     = LOAN_ACCOUNT_NUMBER 
		 ,[THỜI ĐIỂM GIẢI NGÂN] = DISBURSEMENT_DATE   
		 ,[SỐ TIỀN GIẢI NGÂN]   = LOAN_AMOUNT         
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE  


--ĐẶT TÊN BẢNG 

--CÁCH 1 

SELECT 
       X.LOAN_ACCOUNT_NUMBER
	  ,X.LOAN_AMOUNT
	  ,X.CUSTOMER_NAME
FROM [RISK_PORTFOLIO].[dbo].[DIM_CUSTOMER_PROFILE] X


SELECT 
       [1].*
	  ,[1].*
	  ,[1].*
FROM [RISK_PORTFOLIO].[dbo].[DIM_CUSTOMER_PROFILE] [1]


SELECT 
       [1].LOAN_ACCOUNT_NUMBER
	  ,[1].CUSTOMER_NAME
	  ,[1].GENDER
	  ,[1].INCOME
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE [1]

--POSTGRESQL, P/L SQL ORACLE, MYSQL, CLICKHOUSE SQL 

--CÁCH 2 

SELECT 
      RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE.LOAN_ACCOUNT_NUMBER
	 ,RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE.INCOME
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 


--CÂU LỆNH ĐIỀU KIỆN "WHERE"

/*
NHỮNG Predicates and Operators (NÓ BAO GỒM CÁC KÝ HIỆU TOÁN HỌC HOẶC ĐÚNG HƠN LÀ "TOÁN TỬ" VÀ NHỮNG THUẬT TOÁN ĐƯỢC THIẾT KẾ SẴN PHỤC VỤ CHO VIỆC LỌC DỮ LIỆU)
"LIKE", "NOT LIKE", "IN", "NOT IN", "AND", "OR" , "...BETWEEN..AND.." (TƯƠNG ĐƯƠNG VỚI ĐIỀU KIỆN ">= AND <=").

CÁC KÝ HIỆU TOÁN HỌC ỨNG DỤNG VÀO VIỆC LẤY ĐIỀU KIỆN DỮ LIỆU:
1. ( ) (Parentheses)
2. * (Multiplication), / (Division), % (Modulo)
3. + (Positive), – (Negative), + (Addition), + (Concatenation), – (Subtraction)
4. =, >, <, >=, <=, <>, !=, !>, !< (Comparison operators)
5. NOT
6. AND
7. BETWEEN, IN, LIKE, OR
8. = (Assignment or Equal to)

*/

--GỌI NHỮNG "LIKE", "NOT LIKE", "IN", "NOT IN", "AND", "OR" , "...BETWEEN..AND.." (TƯƠNG ĐƯƠNG VỚI ĐIỀU KIỆN ">= AND <=") --> THUẬT TOÁN / Predicates
--GỌI KÝ HIỆU TOÁN HỌC LÀ Operators
--"N" IN HOA VIẾT TẮT CỦA CHỮ NVARCHAR

--KIỂU CHUỖI

--SELECT: CHỌN CỘT DỮ LIỆU TỪ NGUỒN DỮ LIỆU CỤ THỂ LÀ BẢNG DỮ LIỆU 
--FROM: MỆNH ĐỀ LẤY DỮ LIỆU TỪ NGUỒN (CỤ THỂ LÀ BẢNG DỮ LIỆU) NÀO ĐÓ
--WHERE: SỬ DỤNG ĐỂ LỌC ĐIỀU KIỆN CHO CÂU TRUY VẤN
--GROUP BY: KHI MÌNH SỬ DỤNG AGGREGATE FUNCTION (HÀM TỔ HỢP) 
--HAVING: ĐƯỢC DÙNG TRONG TƯỜNG HỢP KHI SỬ DỤNG SUM(), MIN(), MAX(), COUNT(), AVG() LÀM ĐIỀU KIỆN--> VÍ DỤ NHƯ: SUM(PRINCIPAL OUTSTANDING) > 100000000
--ORDER BY : ĐƯỢC SỬ DỤNG KHI MÌNH XẾP HẠNG SORTING KÝ TỰ HOẶC GIÁ TRỊ THEO CỘT DỮ LIỆU



SELECT * FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE  WHERE PROVINCE = N'Hà Nội'  --DẠNG LỌC 1 ĐIỀU KIỆN --N LÀ VIẾT TẮT CỦA NVARCHAR - PHẢI THÊM N NẾU ĐIỀU KIỆN CÓ DẤU

SELECT * FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE  WHERE PROVINCE != N'Hà Nội' --DẠNG LỌC LOẠI TRỪ 1 ĐIỀU KIỆN --N LÀ VIẾT TẮT CỦA NVARCHAR - PHẢI THÊM N NẾU ĐIỀU KIỆN CÓ DẤU --TƯƠNG TỰ TOÁN TỬ <> 

SELECT * FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE  WHERE PROVINCE <> N'Hà Nội' --DẠNG LỌC LOẠI TRỪ 1 ĐIỀU KIỆN --N LÀ VIẾT TẮT CỦA NVARCHAR - PHẢI THÊM N NẾU ĐIỀU KIỆN CÓ DẤU --TƯƠNG TỰ TOÁN TỬ != 

SELECT LOAN_ACCOUNT_NUMBER,PROVINCE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE  WHERE PROVINCE IN (N'Hồ Chí Minh',N'Hà Nội') --DẠNG LỌC 2 ĐIỀU KIỆN TRỞ LÊN

SELECT LOAN_ACCOUNT_NUMBER,PROVINCE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE  WHERE PROVINCE NOT IN (N'Hồ Chí Minh',N'Hà Nội',N'Đà Nẵng') --DẠNG LOẠI TRỪ 2 ĐIỀU KIỆN TRỞ LÊN

SELECT DISTINCT PROVINCE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE  WHERE PROVINCE <= N'Hà Nội' ORDER BY PROVINCE ASC  --(ASCENDING): CÓ Ý NGHĨA LÀ SORTING TĂNG DẦN, VÀ NẾU MUỐN SORTING TĂNG DẦN MÌNH ĐẶT ASC HOẶC "KHÔNG ĐẶT" ĐIỀU ĐƯỢC --> CÓ Ý NGHĨA TĂNG DẦN  --DẠNG LỌC SỬ DỤNG KÝ HIỆU TOÁN HỌC THEO KÝ TỰ ">" & "<" 

SELECT * FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE   WHERE PROVINCE <= N'Hà Nội' ORDER BY PROVINCE DESC --(DESCENDING): CÓ Ý NGHĨA LÀ SORTING GIẢM DẦN --DẠNG LỌC SỬ DỤNG KÝ HIỆU TOÁN HỌC THEO KÝ TỰ ">" & "<" 

SELECT PROVINCE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE PROVINCE = N'Hà Nội' AND  PROVINCE = N'Hồ Chí Minh' --SỬ DỤNG AND CHO TỪ 2 ĐIỀU KIỆN TRỞ LÊN, NHƯNG TRƯỜNG HỢP DÙNG AND CHO CÙNG CỘT DỮ LIỆU THÌ KẾT QUẢ TRẢ VỀ RỖNG

SELECT PROVINCE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE PROVINCE = N'Hà Nội' OR  PROVINCE = N'Hồ Chí Minh'  --SỬ DỤNG OR TRONG TRƯỜNG HỢP LẤY TIÊU CHÍ ĐIỀU KIỆN CÙNG 1 CỘT DỮ LIỆU

SELECT LOAN_ACCOUNT_NUMBER,PROVINCE,GENDER FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE PROVINCE = N'Hà Nội' AND GENDER = N'Nữ'      --SỬ DỤNG AND CHO TỪ 2 ĐIỀU KIỆN TRỞ LÊN, KHÁC CỘT

SELECT INCOME_TYPE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE INCOME_TYPE LIKE '%Business%' --Wildcard          --SỬ DỤNG LIKE ĐỂ LỌC 1 ĐIỀU KIỆN VÀ GIỐNG ĐIỀU KIỆN "=", KẾT HỢP 2 DẤU % ĐỂ LẤY RA KÝ TỰ NẰM TRONG CHUỖI KÝ TỰ MÌNH CẦN LỌC, % BÊN TRÁI VÀ % BÊN PHẢI NGHĨA LÀ BỎ KÝ TỰ Ở BÊN TRÁI VÀ PHẢI ĐỂ LẤY ĐÚNG KÝ TỰ CẦN LỌC

SELECT DISTINCT CUSTOMER_NAME FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE CUSTOMER_NAME LIKE N'Lê%'                      --SỬ DỤNG LIKE KẾT HỢP % LỌC THEO ĐIỀU KIỆN TỪ TRÁI QUA PHẢI VÀ BỎ QUA ĐIỀU KIỆN LỌC BÊN PHẢI

SELECT LOAN_ACCOUNT_NUMBER,PHONE_NUMBER,CUSTOMER_NAME FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE PHONE_NUMBER LIKE '%68'                         --SỬ DỤNG LIKE KẾT HỢP % LỌC THEO ĐIỀU KIỆN TỪ PHẢI QUA TRÁI VÀ BỎ QUA ĐIỀU KIỆN LỌC BÊN TRÁI

SELECT LOAN_ACCOUNT_NUMBER,PROVINCE,INCOME_TYPE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE INCOME_TYPE LIKE '%Payslip%'              --SỬ DỤNG LIKE ĐỂ LỌC 1 ĐIỀU KIỆN VÀ GIỐNG ĐIỀU KIỆN "="

SELECT LOAN_ACCOUNT_NUMBER,PROVINCE,INCOME_TYPE FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE INCOME_TYPE NOT LIKE 'Payslip'          --SỬ DỤNG LIKE ĐỂ LOẠI TRỪ 1 ĐIỀU KIỆN VÀ GIỐNG ĐIỀU KIỆN "!=" và "<>"

SELECT LOAN_ACCOUNT_NUMBER,PROVINCE,INCOME_TYPE,OCCUPATION FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE INCOME_TYPE NOT LIKE 'Payslip' AND OCCUPATION LIKE '%Collar%' --SỬ DỤNG LIKE ĐỂ LỌC TỪ 2 ĐIỀU KIỆN TRỞ LÊN




--TRƯỜNG HỢP LÀ SỐ 

SELECT CUSTOMER_NAME,LOAN_AMOUNT FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE LOAN_AMOUNT <= 50 * POWER(10,6) 


SELECT 
       CUSTOMER_NAME
	  ,LOAN_AMOUNT 
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE LOAN_AMOUNT BETWEEN 50 * POWER(10,6) AND 100 * POWER(10,6) --BETWEEN...AND TƯƠNG ĐƯƠNG VỚI ">= & <="
ORDER BY LOAN_AMOUNT

SELECT 
       *
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE DISBURSEMENT_DATE BETWEEN '2020-01-02' AND '2023-12-31'


--LẤY RA KH ĐƯỢC GIẢI NGÂN VÀO THÁNG 12 NĂM 2023 

SELECT LOAN_ACCOUNT_NUMBER,CUSTOMER_NAME,DISBURSEMENT_DATE,LOAN_AMOUNT FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE MONTH(DISBURSEMENT_DATE) = 12 AND YEAR(DISBURSEMENT_DATE) = 2023


SELECT 
       LOAN_ACCOUNT_NUMBER
	  ,CUSTOMER_NAME
	  ,DISBURSEMENT_DATE
	  ,LOAN_AMOUNT 
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE 1=1
      AND DAY(DISBURSEMENT_DATE) = 31 
      AND MONTH(DISBURSEMENT_DATE) = 12 
      AND YEAR(DISBURSEMENT_DATE) = 2023


SELECT 
       LOAN_ACCOUNT_NUMBER
	  ,CUSTOMER_NAME
	  ,DISBURSEMENT_DATE
	  ,LOAN_AMOUNT 
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE DISBURSEMENT_DATE = '2023-12-31'

--LẤY RA KH ĐƯỢC GIẢI NGÂN VÀO NĂM 2023 VÀ NĂM 2022

SELECT 
        LOAN_ACCOUNT_NUMBER
	   ,CUSTOMER_NAME
	   ,DISBURSEMENT_DATE
	   ,LOAN_AMOUNT 
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE YEAR(DISBURSEMENT_DATE) = 2022

SELECT 
        LOAN_ACCOUNT_NUMBER
	   ,CUSTOMER_NAME
	   ,DISBURSEMENT_DATE
	   ,LOAN_AMOUNT 
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE YEAR(DISBURSEMENT_DATE) = 2023

SELECT 
        LOAN_ACCOUNT_NUMBER
	   ,CUSTOMER_NAME
	   ,DISBURSEMENT_DATE
	   ,LOAN_AMOUNT 
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE YEAR(DISBURSEMENT_DATE) < 2023 

SELECT 
        LOAN_ACCOUNT_NUMBER
	   ,CUSTOMER_NAME
	   ,DISBURSEMENT_DATE
	   ,LOAN_AMOUNT 
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE YEAR(DISBURSEMENT_DATE) > 2023 



--LẤY RA NHỮNG KHÁCH HÀNG ĐƯỢC GIẢI NGÂN TỪ ĐẦU NĂM 2023 ĐẾN GIỮA NĂM CỤ THỂ LÀ CUỐI THÁNG 6 

--DÙNG BETWEEN AND 
SELECT 
       LOAN_ACCOUNT_NUMBER
	  ,CUSTOMER_NAME
	  ,DISBURSEMENT_DATE
	  ,LOAN_AMOUNT 
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE DISBURSEMENT_DATE BETWEEN '2023-01-01' AND '2023-06-30' --">= AND <="
ORDER BY DISBURSEMENT_DATE ASC 


SELECT 
       LOAN_ACCOUNT_NUMBER
	  ,CUSTOMER_NAME 
	  ,DISBURSEMENT_DATE
	  ,LOAN_AMOUNT 
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE DISBURSEMENT_DATE BETWEEN '2023-01-01' AND '2023-06-30'
ORDER BY DISBURSEMENT_DATE DESC 

--DÙNG >= AND <= 

SELECT 
       LOAN_ACCOUNT_NUMBER
	  ,CUSTOMER_NAME
	  ,DISBURSEMENT_DATE
	  ,LOAN_AMOUNT 
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE DISBURSEMENT_DATE >= '2023-01-01' AND DISBURSEMENT_DATE <= '2023-06-30' --">= AND <="
ORDER BY DISBURSEMENT_DATE ASC 


SELECT 
       LOAN_ACCOUNT_NUMBER
	  ,CUSTOMER_NAME 
	  ,DISBURSEMENT_DATE
	  ,LOAN_AMOUNT 
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE DISBURSEMENT_DATE >= '2023-01-01' AND DISBURSEMENT_DATE <= '2023-06-30' --">= AND <="
ORDER BY DISBURSEMENT_DATE DESC 


--KIỂU SỐ 

--LẤY DÙM TÔI NHỮNG KHOẢN VAY TRÊN 100TR 

SELECT LOAN_ACCOUNT_NUMBER,CUSTOMER_NAME,LOAN_AMOUNT FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE LOAN_AMOUNT > 100000000

--LẤY DÙM TÔI NHỮNG KHOẢN VAY TỪ 50TR ĐẾN 100TR 

SELECT LOAN_ACCOUNT_NUMBER,CUSTOMER_NAME,LOAN_AMOUNT FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE LOAN_AMOUNT BETWEEN 50000000 AND 100000000 ORDER BY LOAN_AMOUNT ASC 

SELECT LOAN_ACCOUNT_NUMBER,CUSTOMER_NAME,FORMAT(LOAN_AMOUNT,'#,##0;(#,##0)') AS LOAN_AMOUNT FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE WHERE LOAN_AMOUNT BETWEEN 50000000 AND 100000000 ORDER BY LOAN_AMOUNT DESC 


--LẤY DÙM TÔI TOP 10 NHỮNG KHOẢN VAY DƯỚI 50TR 

SELECT 
       TOP 10
	   LOAN_ACCOUNT_NUMBER
	  ,FORMAT(LOAN_AMOUNT,'#,##0;(#,##0)') AS LOAN_AMOUNT 
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE LOAN_AMOUNT < 50000000 
ORDER BY LOAN_AMOUNT DESC 


--LẤY DÙM TÔI NHỮNG KHÁCH HÀNG ĐƯỢC GIẢI NGÂN TRONG QUÝ 2 NĂM 2023 

SELECT 
       LOAN_ACCOUNT_NUMBER
	  ,DATEPART(QUARTER,DISBURSEMENT_DATE) AS [QUÝ]
	  ,CUSTOMER_NAME
	  ,LOAN_AMOUNT 
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE DATEPART(QUARTER,DISBURSEMENT_DATE) < 3 AND YEAR(DISBURSEMENT_DATE) = 2023


SELECT 
       LOAN_ACCOUNT_NUMBER
	  ,DATEPART(QUARTER,DISBURSEMENT_DATE) AS [QUÝ]
	  ,CUSTOMER_NAME
	  ,LOAN_AMOUNT 
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE 
WHERE DATEPART(QUARTER,DISBURSEMENT_DATE) < 3 AND YEAR(DISBURSEMENT_DATE) = 2023




