
USE RISK_PORTFOLIO 

/*Không sử dụng set điều kiện bằng tay, thiết kế câu Query sao cho tự động theo thời gian mà không phải chỉnh tay*/


/*
  Sử dụng bảng RISK_PORTFOLIO..FACT_LOAN_MANAGEMENT --> CHỐT VỀ "WHERE REPORT_DATE = '2023-12-31'"
  Bài 3: Tổng dư nợ (PRINCIPAL OUTSTANDING ~ ENR (ENDING NET RECEIVABLE)) 
       , Tổng nợ xấu (OUTSTANDING với DPD > 90), Ticket Size (SUM(LOAN_AMOUNT) / COUNT(LOAN_ACCOUNT_NO)) --NPL: NON-PERFORMING LOAN LÀ TỶ LỆ NỢ XẤU
	   , Tổng số tiền WO (OUTSTANDING với DPD > 180)
	   , Tổng khoản vay (LOAN_ACCOUNT_NO) 
	   , Tổng khoản vay bị nợ xấu (Những LOAN_ACCOUNT_NO có DPD > 90) 
	   , Tổng khoản vay bị WO (DPD > 180) 
	   
*/

SELECT
       ---LOGIC DƯ NỢ CỦA NHTM: SẼ TRẢI ĐIỀU TỪ NHÓM 1 ĐẾN NHÓM 5 (NỢ XẤU, NỢ QUÁ HẠN CŨNG LÀ DƯ NỢ...)
       POS          = SUM(OUTSTANDING_AMOUNT)--DƯ NỢ GỐC KHÔNG CÓ LÃI VÀ PHÍ...TÚM LẠI CHỈ LÀ GỐC THÔI..VÀ SẼ GIẢM DẦN NẾU KHÁCH HÀNG ĐÓNG TIỀN
	   ---LOGIC DƯ NỢ CỦA FINTECH/CTY TÀI CHÍNH: SẼ TRẢI ĐIỀU TỪ NHÓM 1 ĐẾN NHÓM 5 (NỢ XẤU, NỢ QUÁ HẠN CŨNG LÀ DƯ NỢ...) - Nhưng riêng phần WO phải bị loại ra. DPD > 180 được xem là WO hoặc có những trường hợp được WO sớm.
	  ,ENR          = SUM(CASE WHEN DPD < 180 THEN OUTSTANDING_AMOUNT ELSE 0 END)

	  --LOGIC NỢ XẤU CỦA NHTM 
	  ,[DPD90+]     = SUM(CASE WHEN DPD > 90 THEN OUTSTANDING_AMOUNT ELSE 0 END)
	  --LOGIC NỢ XẤU CỦA FINTECH/CTY TÀI CHÍNH
	  ,OD3Plus      = SUM(CASE WHEN DPD > 90 AND DPD < 180 THEN OUTSTANDING_AMOUNT ELSE 0 END)
	  ,OD3Plus_CNT  = COUNT(CASE WHEN DPD > 90 AND DPD < 180 THEN LOAN_ACCOUNT_NUMBER END) --NẾU COUNT(...SỐ DÒNG CỦA 1 CỘT THÌ KO ĐƯỢC ELSE...END LUÔN)
	  ,WO_AMOUNT    = SUM(CASE WHEN DPD >= 180 THEN OUTSTANDING_AMOUNT ELSE 0 END)
	  ,WO_CNT       = COUNT(CASE WHEN DPD >= 180 THEN LOAN_ACCOUNT_NUMBER END)
FROM RISK_PORTFOLIO..FACT_LOAN_MANAGEMENT
WHERE REPORT_DATE = '2023-12-31'



--1. Lấy TOP 10 khoản vay có số tiền giải ngân lớn nhất của 2 tháng trước kể từ tháng gần nhất - Sử dụng bảng: [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE].


SELECT TOP 10 
       DISB_MONTH = CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)
      ,LOAN_ACCOUNT_NUMBER
	  ,LOAN_AMOUNT
FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE] 
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) = CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,-2,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE)) FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]))),23)
ORDER BY LOAN_AMOUNT DESC 


SELECT TOP 10 
       DISB_MONTH = CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)
      ,LOAN_ACCOUNT_NUMBER
	  ,LOAN_AMOUNT
FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE] 
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) = CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,-1,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE)) FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]))),23)
ORDER BY LOAN_AMOUNT DESC 


SELECT TOP 10 
       DISB_MONTH = CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)
      ,LOAN_ACCOUNT_NUMBER
	  ,LOAN_AMOUNT
FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE] 
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) = CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,0,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE)) FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]))),23)
ORDER BY LOAN_AMOUNT DESC 



--2. Sản phẩm nào có số tiền giải ngân lớn nhất của tháng gần nhất - Sử dụng bảng: [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE].


SELECT TOP 1
       PRODUCT_NAME
	  ,DISB_AMT = SUM(LOAN_AMOUNT)
FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) = CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,0,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE)) FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]))),23)
GROUP BY PRODUCT_NAME,LOAN_ACCOUNT_NUMBER
ORDER BY SUM(LOAN_AMOUNT) DESC 


--3. Thống kê số tiền giải ngân của mỗi sản phẩm trong 6 tháng gần nhất - Sử dụng bảng: [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE] (Gợi ý sử dụng SUM(CASE WHEN....) cho từng sản phẩm và GROUP BY theo tháng với FORMAT YYYY-MM của DISBURSEMENT_DATE)


--CÁCH 1 																		 


DECLARE @DISB_0 NVARCHAR(7) = CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH, 0,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE)) FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]))),23) 
DECLARE @DISB_1 NVARCHAR(7) = CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,-1,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE)) FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]))),23) 
DECLARE @DISB_2 NVARCHAR(7) = CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,-2,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE)) FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]))),23) 
DECLARE @DISB_3 NVARCHAR(7) = CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,-3,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE)) FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]))),23) 
DECLARE @DISB_4 NVARCHAR(7) = CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,-4,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE)) FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]))),23) 
DECLARE @DISB_5 NVARCHAR(7) = CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,-5,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE)) FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]))),23) 
DECLARE @DISB_6 NVARCHAR(7) = CONVERT(NVARCHAR(7),(SELECT DATEADD(MONTH,-6,(SELECT MAX(EOMONTH(DISBURSEMENT_DATE)) FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]))),23) 



SELECT
       PRODUCT_NAME 
	  ,[DISB_MONTH_T]   = SUM(CASE WHEN CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) = @DISB_0 THEN LOAN_AMOUNT ELSE 0 END) 
	  ,[DISB_MONTH_T-1] = SUM(CASE WHEN CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) = @DISB_1 THEN LOAN_AMOUNT ELSE 0 END) 
	  ,[DISB_MONTH_T-2] = SUM(CASE WHEN CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) = @DISB_2 THEN LOAN_AMOUNT ELSE 0 END) 
	  ,[DISB_MONTH_T-3] = SUM(CASE WHEN CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) = @DISB_3 THEN LOAN_AMOUNT ELSE 0 END) 
	  ,[DISB_MONTH_T-4] = SUM(CASE WHEN CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) = @DISB_4 THEN LOAN_AMOUNT ELSE 0 END) 
	  ,[DISB_MONTH_T-5] = SUM(CASE WHEN CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) = @DISB_5 THEN LOAN_AMOUNT ELSE 0 END) 
	  ,[DISB_MONTH_T-6] = SUM(CASE WHEN CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) = @DISB_6 THEN LOAN_AMOUNT ELSE 0 END) 
FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]
GROUP BY PRODUCT_NAME

--CÁCH 2 

SELECT 
       CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23) AS [PERIOD]
      ,SUM(CASE WHEN PRODUCT_NAME = 'G-Gold' THEN LOAN_AMOUNT ELSE 0 END) AS 'G-Gold'
      ,SUM(CASE WHEN PRODUCT_NAME = 'T-Titanium' THEN LOAN_AMOUNT ELSE 0 END) AS 'T-Titanium'
      ,SUM(CASE WHEN PRODUCT_NAME = 'B-BROWN' THEN LOAN_AMOUNT ELSE 0 END) AS 'B-BROWN'
      ,SUM(CASE WHEN PRODUCT_NAME = 'INSURANCE' THEN LOAN_AMOUNT ELSE 0 END) AS 'INSURANCE'
      ,SUM(CASE WHEN PRODUCT_NAME = 'VAY_PLUS' THEN LOAN_AMOUNT ELSE 0 END) AS 'VAY_PLUS'
FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE
WHERE CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)> CONVERT(NVARCHAR(7),(SELECT EOMONTH(CAST(MAX(DISBURSEMENT_DATE) AS DATE),-7) FROM RISK_PORTFOLIO..DIM_CUSTOMER_PROFILE),23)
GROUP BY CONVERT(NVARCHAR(7),DISBURSEMENT_DATE,23)


--4. Tỉnh nào có nhiều khoản vay nhất vào năm ngoái - Sử dụng bảng: [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE].


SELECT TOP 1
       PROVINCE 
	  ,ACCT_CNT = COUNT(LOAN_ACCOUNT_NUMBER)
FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE] 
WHERE YEAR(DISBURSEMENT_DATE) = (SELECT YEAR(DATEADD(YEAR,-1,(SELECT MAX(DISBURSEMENT_DATE) FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]))))
GROUP BY PROVINCE
ORDER  BY COUNT(LOAN_ACCOUNT_NUMBER) DESC 


--5. Lấy TOP 10 tỉnh có số tiền giải ngân vào Quý 1 và Quý 2 năm ngoái - Sử dụng bảng: [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE].

--QUÝ 1

SELECT TOP 10 
       [QUARTER] = CONCAT('QUARTER',' - ',DATEPART(QUARTER,DISBURSEMENT_DATE),' - ',YEAR(DISBURSEMENT_DATE))
      ,PROVINCE 
	  ,DISB_AMT  = SUM(LOAN_AMOUNT)
FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE] 
WHERE 1=1 
      AND YEAR(DISBURSEMENT_DATE) = (SELECT YEAR(DATEADD(YEAR,-1,(SELECT MAX(DISBURSEMENT_DATE) FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]))))--NĂM NGOÁI
	  AND DATEPART(QUARTER,DISBURSEMENT_DATE) = 1 --QUÝ 1
GROUP BY PROVINCE, CONCAT('QUARTER',' - ',DATEPART(QUARTER,DISBURSEMENT_DATE),' - ',YEAR(DISBURSEMENT_DATE))
ORDER BY SUM(LOAN_AMOUNT) DESC 


--QUÝ 2

SELECT TOP 10 
       [QUARTER] = CONCAT('QUARTER',' - ',DATEPART(QUARTER,DISBURSEMENT_DATE),' - ',YEAR(DISBURSEMENT_DATE))
      ,PROVINCE 
	  ,DISB_AMT = SUM(LOAN_AMOUNT)
FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE] 
WHERE 1=1 
      AND YEAR(DISBURSEMENT_DATE) = (SELECT YEAR(DATEADD(YEAR,-1,(SELECT MAX(DISBURSEMENT_DATE) FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE]))))--NĂM NGOÁI
	  AND DATEPART(QUARTER,DISBURSEMENT_DATE) = 2 --QUÝ 1
GROUP BY PROVINCE, CONCAT('QUARTER',' - ',DATEPART(QUARTER,DISBURSEMENT_DATE),' - ',YEAR(DISBURSEMENT_DATE))
ORDER BY SUM(LOAN_AMOUNT) DESC 





--6. Lấy ENR và WO amount theo tháng (chốt cuối tháng: REPORT_DATE = EOMONTH(REPORT_DATE)) - Sử dụng bảng: [RISK_PORTFOLIO]..[FACT_LOAN_MANAGEMENT] (Gợi ý sử dụng SUM(CASE WHEN....) cho từng điều kiện ENR và WO theo tháng với chốt cuối tháng của REPORT_DATE)
			/*
			   ENR: DPD < 180 
			   WO: DPD >= 180 
			*/

SELECT
       REPORT_DATE
       ---LOGIC DƯ NỢ CỦA NHTM: SẼ TRẢI ĐIỀU TỪ NHÓM 1 ĐẾN NHÓM 5 (NỢ XẤU, NỢ QUÁ HẠN CŨNG LÀ DƯ NỢ...)
      ,POS          = SUM(OUTSTANDING_AMOUNT)--DƯ NỢ GỐC KHÔNG CÓ LÃI VÀ PHÍ...TÚM LẠI CHỈ LÀ GỐC THÔI..VÀ SẼ GIẢM DẦN NẾU KHÁCH HÀNG ĐÓNG TIỀN
	   ---LOGIC DƯ NỢ CỦA FINTECH/CTY TÀI CHÍNH: SẼ TRẢI ĐIỀU TỪ NHÓM 1 ĐẾN NHÓM 5 (NỢ XẤU, NỢ QUÁ HẠN CŨNG LÀ DƯ NỢ...) - Nhưng riêng phần WO phải bị loại ra. DPD > 180 được xem là WO hoặc có những trường hợp được WO sớm.
	  ,ENR          = SUM(CASE WHEN DPD < 180 THEN OUTSTANDING_AMOUNT ELSE 0 END)
	  ,WO_AMOUNT    = SUM(CASE WHEN DPD >= 180 THEN OUTSTANDING_AMOUNT ELSE 0 END)
	  ,WO_CNT       = COUNT(CASE WHEN DPD >= 180 THEN LOAN_ACCOUNT_NUMBER END)
FROM RISK_PORTFOLIO..FACT_LOAN_MANAGEMENT
WHERE REPORT_DATE = EOMONTH(REPORT_DATE)
GROUP BY REPORT_DATE


--7. Lập báo cáo giải ngân theo tuần - theo dõi SẢN PHẨM, GIỚI TÍNH, TỈNH THÀNH, KHU VỰC, LOẠI THU NHẬP - Sử dụng bảng: [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE].

DECLARE @REPORT_DATE DATE = (SELECT MAX(EOMONTH(DISBURSEMENT_DATE)) FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE])
DECLARE @WEEK4 DATE = (SELECT DATEADD(DAY,-7,@REPORT_DATE)) 
DECLARE @WEEK3 DATE = (SELECT DATEADD(DAY,-7,@WEEK4)) 
DECLARE @WEEK2 DATE = (SELECT DATEADD(DAY,-7,@WEEK3)) 
DECLARE @WEEK1 DATE = (SELECT DATEADD(DAY,-7,@WEEK2)) 
DECLARE @WEEK0 DATE = (SELECT DATEADD(DAY,-7,@WEEK1)) 


SELECT
       PRODUCT_NAME
	  ,[WEEK4] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK4 AND DISBURSEMENT_DATE > @WEEK3 THEN LOAN_AMOUNT ELSE 0 END)
	  ,[WEEK3] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK3 AND DISBURSEMENT_DATE > @WEEK2 THEN LOAN_AMOUNT ELSE 0 END)
	  ,[WEEK2] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK2 AND DISBURSEMENT_DATE > @WEEK1 THEN LOAN_AMOUNT ELSE 0 END)
	  ,[WEEK1] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK1 AND DISBURSEMENT_DATE > @WEEK0 THEN LOAN_AMOUNT ELSE 0 END)
FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE] 
GROUP BY PRODUCT_NAME

SELECT
       GENDER
	  ,[WEEK4] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK4 AND DISBURSEMENT_DATE > @WEEK3 THEN LOAN_AMOUNT ELSE 0 END)
	  ,[WEEK3] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK3 AND DISBURSEMENT_DATE > @WEEK2 THEN LOAN_AMOUNT ELSE 0 END)
	  ,[WEEK2] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK2 AND DISBURSEMENT_DATE > @WEEK1 THEN LOAN_AMOUNT ELSE 0 END)
	  ,[WEEK1] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK1 AND DISBURSEMENT_DATE > @WEEK0 THEN LOAN_AMOUNT ELSE 0 END)
FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE] 
GROUP BY GENDER

SELECT
       PROVINCE
	  ,[WEEK4] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK4 AND DISBURSEMENT_DATE > @WEEK3 THEN LOAN_AMOUNT ELSE 0 END)
	  ,[WEEK3] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK3 AND DISBURSEMENT_DATE > @WEEK2 THEN LOAN_AMOUNT ELSE 0 END)
	  ,[WEEK2] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK2 AND DISBURSEMENT_DATE > @WEEK1 THEN LOAN_AMOUNT ELSE 0 END)
	  ,[WEEK1] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK1 AND DISBURSEMENT_DATE > @WEEK0 THEN LOAN_AMOUNT ELSE 0 END)
FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE] 
GROUP BY PROVINCE
 
SELECT
       INCOME_TYPE
	  ,[WEEK4] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK4 AND DISBURSEMENT_DATE > @WEEK3 THEN LOAN_AMOUNT ELSE 0 END)
	  ,[WEEK3] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK3 AND DISBURSEMENT_DATE > @WEEK2 THEN LOAN_AMOUNT ELSE 0 END)
	  ,[WEEK2] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK2 AND DISBURSEMENT_DATE > @WEEK1 THEN LOAN_AMOUNT ELSE 0 END)
	  ,[WEEK1] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK1 AND DISBURSEMENT_DATE > @WEEK0 THEN LOAN_AMOUNT ELSE 0 END)
FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE] 
GROUP BY INCOME_TYPE

SELECT
       REGION
	  ,[WEEK4] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK4 AND DISBURSEMENT_DATE > @WEEK3 THEN LOAN_AMOUNT ELSE 0 END)
	  ,[WEEK3] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK3 AND DISBURSEMENT_DATE > @WEEK2 THEN LOAN_AMOUNT ELSE 0 END)
	  ,[WEEK2] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK2 AND DISBURSEMENT_DATE > @WEEK1 THEN LOAN_AMOUNT ELSE 0 END)
	  ,[WEEK1] = SUM(CASE WHEN DISBURSEMENT_DATE <= @WEEK1 AND DISBURSEMENT_DATE > @WEEK0 THEN LOAN_AMOUNT ELSE 0 END)
FROM [RISK_PORTFOLIO]..[DIM_CUSTOMER_PROFILE] 
GROUP BY REGION











